# Generated by Django 5.0.6 on 2024-09-16 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0002_alter_user_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.DecimalField(decimal_places=5, max_digits=5)),
                ('Gender', models.CharField(max_length=50)),
                ('Weight', models.FloatField()),
                ('Height', models.FloatField()),
                ('FitnessLevel', models.CharField(max_length=100)),
                ('Goal', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flexfit.user')),
            ],
        ),
    ]
