# Generated by Django 5.0.6 on 2024-09-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0003_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexfit.user'),
        ),
    ]
