# Generated by Django 5.0.6 on 2024-09-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0004_alter_information_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Age',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='information',
            name='Height',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='information',
            name='Weight',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
