# Generated by Django 5.0.6 on 2024-09-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0005_alter_information_age_alter_information_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
