# Generated by Django 5.0.6 on 2024-09-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='Fat',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
