# Generated by Django 5.0.6 on 2024-09-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0007_information_fat'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='Active_Level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='BMR_Calories',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='TDEE_Calorie',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
