# Generated by Django 5.0.6 on 2024-09-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0008_information_active_level_information_bmr_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='Calorie_Daily',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='Carb_Daily',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='Fat_Daily',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='Protein_Daily',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
