# Generated by Django 5.0.6 on 2024-09-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0011_rename_average_calorie_information_calorie_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Image/')),
            ],
        ),
    ]
