# Generated by Django 5.0.6 on 2024-10-02 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0012_scanimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking_Calorie_Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Update_Status', models.BooleanField()),
                ('Calorie_Daily', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Protein_Daily', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Carb_Daily', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Fat_Daily', models.DecimalField(decimal_places=1, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexfit.user')),
            ],
        ),
    ]
