# Generated by Django 5.0.6 on 2024-10-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0013_tracking_calorie_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_calorie_daily',
            name='Carb_Percentage',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking_calorie_daily',
            name='Fat_Percentage',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking_calorie_daily',
            name='Pertein_Percentage',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
