# Generated by Django 5.0.6 on 2024-10-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0014_tracking_calorie_daily_carb_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_calorie_daily',
            name='Calorie_Percentage',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
