# Generated by Django 5.0.6 on 2024-10-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0015_tracking_calorie_daily_calorie_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking_calorie_daily',
            old_name='Pertein_Percentage',
            new_name='Protein_Percentage',
        ),
    ]
