# Generated by Django 5.0.6 on 2024-10-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0018_rename_calorie_daily_tracking_calorie_daily_calorie_daily_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=5000)),
                ('Type', models.CharField(max_length=100)),
                ('Send_at', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexfit.user')),
            ],
        ),
    ]
