# Generated by Django 5.0.6 on 2024-10-11 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0019_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MealPlan_Status', models.BooleanField()),
                ('Meal_Type', models.CharField(max_length=100)),
                ('FoodName', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('Calorie', models.CharField(max_length=100)),
                ('Notes', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexfit.user')),
            ],
        ),
    ]
