# Generated by Django 5.0.6 on 2024-10-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0020_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='Carb',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='Fat',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='Protein',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
