# Generated by Django 5.0.6 on 2024-10-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0021_mealplan_carb_mealplan_fat_mealplan_protein'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
