# Generated by Django 5.0.6 on 2024-10-31 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0022_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='uploaded_at',
            new_name='Uploaded_at',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='Video',
        ),
    ]
