# Generated by Django 5.0.6 on 2024-10-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0023_rename_category_video_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Category',
            new_name='Video_Category',
        ),
    ]
