# Generated by Django 5.0.6 on 2024-10-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0025_rename_video_category_video_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Category',
            new_name='category',
        ),
    ]
