# Generated by Django 5.0.6 on 2024-10-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0026_rename_category_video_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='category',
            new_name='Category',
        ),
    ]
