# Generated by Django 5.0.6 on 2024-11-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0027_rename_category_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='Image_url',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
