# Generated by Django 5.0.6 on 2024-11-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0028_mealplan_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Thumbnail',
            field=models.ImageField(default=1, upload_to='videos_thumbnail/'),
            preserve_default=False,
        ),
    ]
