# Generated by Django 5.0.6 on 2024-11-05 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfit', '0030_video_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QR_Code', models.ImageField(upload_to='QR_Code/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexfit.user')),
            ],
        ),
    ]
